name: prctr-hsa-hw10
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.templates.enabled=true
    ports:
      - '9200:9200'
    volumes:
      - es01_data:/usr/share/elasticsearch/data

  kib01:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on: ["es01"]

  jumpbox:
    build: ./jumpbox
    ports:
      - "8888:8888"
    volumes:
      - ./jumpbox:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    depends_on: ["kib01", "es01"]

volumes:
  es01_data: {}
